const allProduct=[
    {
        id:1,
        name:"Weddig party wear Bandi",
        img:"https://images.cottonduniya.com/image/800/1554411898166332107764139999-Peach%20Colour%20Outluk%20Vol%2085%20New%20Latest%20Designer%20party%20Wear%20Velvet%20Jodhpuri%20Suit%20Collection%2085001.jpg",
        new_Price:"800",
        old_Price:"1200",
        discount:"33%",
        ratings:"4",
        rateno:"12,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:2,
        name:"Casual Cotton Sleeves",
        img:"https://img.freepik.com/free-photo/full-length-portrait-handsome-serious-man_171337-17388.jpg?size=626&ext=jpg&ga=GA1.1.632798143.1705708800&semt=ais",
        new_Price:"600",
        old_Price:"1300",
        discount:"49%",
        ratings:"4.2",
        rateno:"1,400",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:3,
        name:"Cool Cotton Clothes",
        img:"https://www.bonsoir.co.in/cdn/shop/products/BLAZERB-220_3_large.jpg?v=1648618126",
        new_Price:"1200",
        old_Price:"2000",
        discount:"40%",
        ratings:"4.3",
        rateno:"22,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:4,
        name:"Casual Cotton T-Shirt",
        img:"https://www.manyavar.com/on/demandware.static/-/Library-Sites-ManyavarSharedLibrary/default/dwe5e21f1c/images/feeds/UC100713.jpg",
        new_Price:"500",
        old_Price:"800",
        discount:"36%",
        ratings:"4.1",
        rateno:"2,00,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:5,
        name:"Cool Stunning Summer Shirt ",
        img:"https://static3.azafashions.com/tr:w-317/uploads/product_gallery/1630507-0225431001652788794.jpg?noopt=true",
        new_Price:"600",
        old_Price:"1200",
        discount:"50%",
        ratings:"4.5",
        rateno:"32,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:6,
        name:"Stunning Celeb Choice Coat",
        img:"https://i.pinimg.com/originals/83/d7/60/83d7605e80958154b3321d5cf9759c4d.jpg",
        new_Price:"1000",
        old_Price:"1500",
        discount:"33.3%",
        ratings:"4.4",
        rateno:"62,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:7,
        name:"Weddig party Blue Bandi",
        img:"https://5.imimg.com/data5/SELLER/Default/2023/2/HX/EP/LO/184477421/mens-dress-shirts-500x500.jpeg",
        new_Price:"800",
        old_Price:"1200",
        discount:"33%",
        ratings:"4",
        rateno:"11,2000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:8,
        name:"Office Court Look",
        img:"https://wendellrodricks.b-cdn.net/pub/media_wr/catalog/product/w/r/WRMD0422550_3.jpg?tr=true&width=585&height=878",
        new_Price:"600",
        old_Price:"1300",
        discount:"49%",
        ratings:"4.2",
        rateno:"1,20,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:9,
        name:"Stylish RayMond Court",
        img:"https://cdn0.weddingwire.in/article/1112/original/1280/jpg/102111-reception-dress-for-men-5.jpeg",
        old_Price:"2000",
        discount:"40%",
        ratings:"4.3",
        rateno:"12,2000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:10,
        name:"Traditional Men's Wear",
        img:"https://medias.utsavfashion.com/blog/wp-content/uploads/2023/05/traditional-menswear.jpg",
        new_Price:"500",
        old_Price:"800",
        discount:"36%",
        ratings:"4.1",
        rateno:"18,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:11,
        name:"Cool Wedding Wear",
        img:"https://4.imimg.com/data4/LS/DG/MY-26718186/mens-formal-waistcoat.jpg",
        new_Price:"600",
        old_Price:"1200",
        discount:"50%",
        ratings:"4.5",
        rateno:"15,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:12,
        name:"Casual Shirt Pants",
        img:"https://i.etsystatic.com/28504096/r/il/a2df1d/4795630119/il_570xN.4795630119_ex97.jpg",
        new_Price:"1000",
        old_Price:"1500",
        discount:"33.3%",
        ratings:"4.4",
        rateno:"62,000",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"male"
    },
    {
        id:13,
        name:"Beautiful Flaunting Gown",
        img:"https://i.pinimg.com/originals/4a/4f/28/4a4f28494cc7549910d1a70567a639b0.jpg",
        new_Price:"800",
        old_Price:"1200",
        discount:"33%",
        ratings:"4",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:14,
        name:"Classy Awesome Outfit",
        img:"https://kaleendi.com/wp-content/uploads/2022/02/rosy-pink-gownnnn-600x600.jpg",
        new_Price:"1000",
        old_Price:"2000",
        discount:"50%",
        ratings:"4.8",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:15,
        name:"Beautiful Party Gown",
        img:"https://www.alamodelabel.in/cdn/shop/files/image_c7ea1d85-0c90-4efb-b661-8ff2e38730a7_600x.jpg?v=1689689393",
        new_Price:"2000",
        old_Price:"2500",
        discount:"20%",
        ratings:"4.5",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:16,
        name:"Bold Office Wear",
        img:"https://d2w9m16hs9jc37.cloudfront.net/dimg/blog/2023/08/hockerty_business_casual_outfits_for_woman_013a099b_0b8b_43a2_886f_754716f88f1a.png",
        new_Price:"1000",
        old_Price:"1500",
        discount:"33%",
        ratings:"4.2",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:17,
        name:"Awesome Casual Wear",
        img:"https://sslimages.shoppersstop.com/sys-master/images/h9b/h45/28560065789982/AW22HCT145_MOUSE_alt1.jpg_2000Wx3000H",
        new_Price:"900",
        old_Price:"1200",
        discount:"33.33%",
        ratings:"4",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:18,
        name:"Pretty Skirt",
        img:"https://assets.myntassets.com/h_1440,q_100,w_1080/v1/assets/images/4914118/2018/6/7/55487e87-b14b-49a8-a0ac-f7d88b78a5051528372773678-HERENOW-Women-Skirts-1971528372773513-1.jpg",
        new_Price:"800",
        old_Price:"1600",
        discount:"50%",
        ratings:"4.5",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:19,
        name:"Beautiful Red Gown",
        img:"https://n.nordstrommedia.com/id/sr3/0c67d797-45bd-4110-bf56-790ca959246a.jpeg?h=365&w=240&dpr=2",
        new_Price:"800",
        old_Price:"1200",
        discount:"33%",
        ratings:"4",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:20,
        name:"Classy korean Outfit",
        img:"https://www.lovebonito.com/cdn-cgi/image/width=300,format=webp,quality=80/https://a.storyblok.com/f/126880/428x600/0e4417ad1d/plp_jul_dresses_wedding-party.jpg",
        new_Price:"1000",
        old_Price:"2000",
        discount:"50%",
        ratings:"4.8",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:21,
        name:"Beautiful grey Skirt",
        img:"https://assets.ajio.com/medias/sys_master/root/20230621/TZxK/64925fe142f9e729d7637801/azira_pink_floral_a-line_dress.jpg",
        new_Price:"2000",
        old_Price:"2500",
        discount:"20%",
        ratings:"4.5",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:22,
        name:"Awesome Green Dress",
        img:"https://assets.ajio.com/medias/sys_master/root/20220813/kOMJ/62f6b877aeb26921afe841e6/-473Wx593H-463002599-green-MODEL.jpg",
        new_Price:"1000",
        old_Price:"1500",
        discount:"33%",
        ratings:"4.2",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:23,
        name:"Slim Fit-OutFit",
        img:"https://images-na.ssl-images-amazon.com/images/I/611yBgmAvxL.jpg",
        new_Price:"900",
        old_Price:"1200",
        discount:"33.33%",
        ratings:"4",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"
    },
    {
        id:24,
        name:"Preety Blue Dress",
        img:"https://i.etsystatic.com/7799304/r/il/f24aef/2105739985/il_570xN.2105739985_1bc7.jpg",
        new_Price:"800",
        old_Price:"1600",
        discount:"50%",
        ratings:"4.5",
        brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        category:"female"

    },
    {
    id:25,
    name:"Cool Kids SweatShirts",
    img:"https://5.imimg.com/data5/SELLER/Default/2023/9/347112195/DK/TK/BQ/23831093/ameeha-hoodie-sweatshirt-sweatpant-kids-winter-dress-clothing-set-for-boys-girls-500x500.jpg",
    new_Price:"800",
    old_Price:"1200",
    discount:"33%",
    ratings:"4",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:26,
    name:"Kids Wedding Party Wear",
    img:"https://assets0.mirraw.com/images/11655979/Pink_Blue_Front___Final_front_11_long_webp.webp?1696930980",
    new_Price:"900",
    old_Price:"1500",
    discount:"60%",
    ratings:"4.1",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:27,
    name:"Cute Party Coat",
    img:"https://i.pinimg.com/736x/8d/2c/da/8d2cda486dbcc66e0f0e552509b20357.jpg",
    new_Price:"900",
    old_Price:"1200",
    discount:"25%",
    ratings:"4.4",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:28,
    name:"Cute Night Wear Set",
    img:"https://berrytree.in/cdn/shop/products/BTBOY-517-4_400x.jpg?v=1637924949",
    new_Price:"1000",
    old_Price:"1600",
    discount:"36%",
    ratings:"4.5",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:29,
    name:"kids Casual T-Shirt",
    img:"https://assets.ajio.com/medias/sys_master/root/20230623/7Lhz/6494bbecd55b7d0c63a39b69/-473Wx593H-464402062-blue-MODEL.jpg",
    new_Price:"200",
    old_Price:"500",
    discount:"60%",
    ratings:"3.8",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:30,
    name:"Party Casual Set",
    img:"https://rukminim2.flixcart.com/image/550/650/xif0q/kids-dungaree-romper/7/c/0/2-3-years-suspender-dungaree-set-purplesky-original-imagq67h3qyhraj3.jpeg?q=90&crop=true",
    new_Price:"900",
    old_Price:"1200",
    discount:"25%",
    ratings:"3.8",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:31,
    name:"Funky cool Jacket 🤩",
    img:"https://www.okboss.co.in/assets/img/home/boysrow1/kids%20musterd%20jacket%20with%20white%20tshirt%20party%20wear%20dress.jpg",
    new_Price:"800",
    old_Price:"1200",
    discount:"33%",
    ratings:"4",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:32,
    name:"Cool Joging Set😎",
    img:"https://m.media-amazon.com/images/I/51gUyrreAxL._AC_UF894,1000_QL80_.jpg",
    new_Price:"900",
    old_Price:"1500",
    discount:"60%",
    ratings:"4.1",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:33,
    name:"Wedding kurta👌",
    img:"https://assets0.mirraw.com/images/11701931/grey_front_long_webp.webp?1696935243",
    new_Price:"900",
    old_Price:"1200",
    discount:"25%",
    ratings:"4.4",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:34,
    name:"Party Wear",
    img:"https://m.media-amazon.com/images/I/51w0MBRefoL._AC_UY350_.jpg",
    new_Price:"1000",
    old_Price:"1600",
    discount:"36%",
    ratings:"4.5",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:35,
    name:"Casual Formal Shirt ✌️",
    img:"https://thumbs.dreamstime.com/z/little-boy-wear-formal-clothes-cute-boy-serious-event-outfit-impeccable-style-happy-childhood-kids-fashion-small-businessman-152224763.jpg",
    new_Price:"200",
    old_Price:"500",
    discount:"60%",
    ratings:"3.8",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
},
{
    id:36,
    name:"Wedding Kurta",
    img:"https://5.imimg.com/data5/FI/WB/MY-50477541/kids-boys-blue-indo-western-dress.jpg",
    new_Price:"900",
    old_Price:"1200",
    discount:"25%",
    ratings:"3.8",
    brief:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
    category:"kids"
}
]

export default allProduct;